[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "functions-build"

[functions]
  directory = "functions-build"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
