name: Node.js CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test:unit
        env:
          NODE_ENV: test
          JEST_TIMEOUT: 10000

  ui-tests:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb tree
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Create required directories and files
        run: |
          # Create base directories
          mkdir -p public lambda/views data
          
          # Initialize data file
          echo '[]' > data/users.json
          
          # Create views in the correct location
          mkdir -p lambda/views
          
          # Create signup view
          cat > lambda/views/signup.ejs << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Sign Up</title>
          </head>
          <body>
              <h1>Sign Up</h1>
              <% if (error) { %>
                  <div style="color: red;"><%= error %></div>
              <% } %>
              <form action="/signup" method="POST">
                  <div>
                      <label>Username:</label>
                      <input type="text" name="username" required>
                  </div>
                  <div>
                      <label>Email:</label>
                      <input type="email" name="email" required>
                  </div>
                  <div>
                      <label>Password:</label>
                      <input type="password" name="password" required>
                  </div>
                  <button type="submit">Sign Up</button>
              </form>
          </body>
          </html>
          EOL
          
          # Create login view
          cat > lambda/views/login.ejs << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Login</title>
          </head>
          <body>
              <h1>Login</h1>
              <% if (error) { %>
                  <div style="color: red;"><%= error %></div>
              <% } %>
              <form action="/login" method="POST">
                  <div>
                      <label>Username:</label>
                      <input type="text" name="username" required>
                  </div>
                  <div>
                      <label>Password:</label>
                      <input type="password" name="password" required>
                  </div>
                  <button type="submit">Login</button>
              </form>
          </body>
          </html>
          EOL
          
          # Verify directory structure
          echo "Directory structure:"
          tree .
          
          # Verify views content
          echo "\nViews content:"
          ls -la lambda/views/
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
      - name: Start server and verify
        run: |
          npm start > server.log 2>&1 &
          echo "Waiting for server to start..."
          npx wait-on -t 30000 -v http://localhost:9000/signup
          echo "Server is ready"
          curl -v http://localhost:9000/signup || true
          echo "Current directory contents:"
          ls -la
          echo "Views directory contents:"
          ls -la views/
          echo "Server logs:"
          cat server.log
      - name: Run UI tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" npm run test:ui
        env:
          DEBUG: pw:api
          CI: true
      - name: Upload server logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-logs
          path: server.log
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    needs: [build-and-test, ui-tests]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
